"http://gmarik.info/blog/2011/05/17/chicken-or-egg-dilemma
source ~/.vim/bundles.vim

syntax on
set t_Co=16
set bg=light
colorscheme solarized
"colorscheme ir_black
"colorscheme Tomorrow-Night


set number
set ruler

set colorcolumn=80 "only works on Vim 7.3 and up
set showmode
set showcmd

set laststatus=2

" Indenting and tabbing
" tabs are 4 spaces
set autoindent
set softtabstop=4
set shiftwidth=4
set expandtab

"No folding!
set nofoldenable

" Search
set hlsearch
set showmatch

set cursorline

"Tabbed completion
function! Tab_Complete_Wrapper(direction)
   let col = col('.') - 1
   if !col || strpart( getline('.'), col('.')-2, 3 ) !~ '^\w'
       return "\<tab>"
   elseif "backward" == a:direction
       return "\<c-p>"
   else
       return "\<c-n>"
   endif
endfunction
inoremap <tab> <c-r>=Tab_Complete_Wrapper("forward")<cr>
inoremap <s-tab> <c-r>=Tab_Complete_Wrapper("backward")<cr>

"remap jj to escape
:imap jj <Esc>

" file specific stuff
au BufRead,BufNewFile *.json set filetype=javascript
au BufNewFile,BufReadPost *.coffee setl shiftwidth=2 tabstop=2 expandtab
au BufNewFile,BufReadPost *.clj setl shiftwidth=2 tabstop=2 expandtab
